name: Spam

on: issue_comment
jobs:
  mark-as-spam:
    name: mark as spam
    runs-on: ubuntu-latest
    steps:
      - name: close issue
        uses: balevine/mark-as-spam@production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
